<?php
/**
 * @file
 * meeting_minutes.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function meeting_minutes_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_committee_or_publication'.
  $field_bases['field_committee_or_publication'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_committee_or_publication',
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'CD' => 'Collections Development',
        'COMM' => 'Communications Committee',
        'ISC' => 'Instructional Services Committee',
        'LCSWG' => 'John B. McNair Learning Commons Services Committee',
        'LB' => 'Library Board',
        'LMG' => 'Library Management Group',
        'PSC' => 'Public Service Committee',
        'SLC' => 'Senate Library Committee',
        'SAC' => 'Student Advisory Council',
        'STDC' => 'Staff Training & Development Committee',
        'WERC' => 'Web & Electronic Resources Committee',
        'WRC' => 'Website Review Committee',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_date_of_meeting'.
  $field_bases['field_date_of_meeting'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_date_of_meeting',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'date',
    'settings' => array(
      'cache_count' => 4,
      'cache_enabled' => 0,
      'granularity' => array(
        'day' => 'day',
        'hour' => 0,
        'minute' => 0,
        'month' => 'month',
        'second' => 0,
        'year' => 'year',
      ),
      'timezone_db' => '',
      'todate' => '',
      'tz_handling' => 'none',
    ),
    'translatable' => 0,
    'type' => 'datetime',
  );

  // Exported field_base: 'field_minutes_file'.
  $field_bases['field_minutes_file'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_minutes_file',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'file',
    'settings' => array(
      'display_default' => 0,
      'display_field' => 0,
      'uri_scheme' => 'private',
    ),
    'translatable' => 0,
    'type' => 'file',
  );

  // Exported field_base: 'field_special_note'.
  $field_bases['field_special_note'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_special_note',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 15,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
